version: '3'
services:
  docker_mysql:
    image: 'mysql:latest'
    container_name: docker_mysql
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_DATABASE=db_example'
    ports:
      - '3307:3306'
    volumes:
      - "/home/docker/volumes/myapp/mysql/:/var/lib/mysql/"
  docker_spring_boot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - docker_mysql
    container_name: docker_spring_boot
    restart: 'no'
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker_mysql:3306/db_example?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true

